config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :posts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  get '/favorites', to: 'favorites#index'
  
  resources :posts do
    collection do
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
    
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :picture, ImageUploader
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts
    has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index
        @favorites = current_user.favorites.all
    end
    def create
        favorite = current_user.favorites.create(post_id: params[:post_id])
        redirect_to posts_url, notice: "#{favorite.post.user.name}'s post has been favorited"
    end
    def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to posts_url, notice: "#{favorite.post.user.name}'s post has been unfavored"
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
    unless session[:user_id] == @post.user_id
      flash[:notice] = "Sorry this is not your post so you cannot edit it."
      redirect_to posts_path(session[:user_id])
      return
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        # ContactMailer.contact_mail(@post).deliver
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :content, :user_id, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:danger] = 'Failed to login'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end
 
  def edit
    @user = User.find params[:id]
    unless session[:user_id] == @user.id
      flash[:notice] = "Sorry you cannot edit this user."
      redirect_to users_path(session[:user_id])
      return
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

    
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'new'
          confirm_posts_path
        elsif action_name == 'edit'
          post_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/views/favorites/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.post.user.name %></td>
        <td><%= image_tag favorite.post.image.url, style:"width:250px"%></td>
        <td><%= favorite.post.content %></td>       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to posts', posts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="top">
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %> |
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %> |
      <%= link_to "Login", new_session_path %>
    <% end %>
    </div>
    <%= yield %>
    <footer>
      <p>© 2020 Copyright Instagram clone project</p>
    </footer> 
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/confirm.html.erb
<div class="container">
<h1>Confirmation screen</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>Content:<%= @post.content %></p>
  
  <%= form.submit "Post" %>
  
<% end %>
 <br>
<%= form_with(model:@post, url: new_post_path, local:true, method: 'get') do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'List of posts', posts_path %>

</div>

app/views/posts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      
      <tr>
        <td><%= post.user.name %></td>
        <td><%= image_tag post.image.url, style:"width:250px"%></td>
        <td><%= post.content %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Show', post %></button></td>
        <% if session[:user_id] == post.user.id %>
        <td><button type="button" class="btn btn-warning" ><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <%else%>
        <td><button type="button" class="btn btn-warning hidden" ><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><button type="button" class="btn btn-danger hidden"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <%end%>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-success"><%= link_to 'New Post', new_post_path %></button> |
<button type="button" class="btn btn-info"><%= link_to 'Favorites', favorites_path %></button>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url, size: 17*17 %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Cancel favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Make it a favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% if session[:user_id] == @post.user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%end%>
<%= link_to 'List of posts', posts_path %>

</div>

app/views/users/_form.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :picture %>
  <%= f.file_field :picture %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<div class ="container">

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'List of posts', posts_path %>
</div>

app/views/users/new.html.erb
<div class ="container">
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', new_session_path %>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p> 
  <strong>Picture:</strong>
  <%= image_tag @user.picture.url, size: 13*13  %>
</p>

<% if logged_in? %>
  <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_user_path(@user) %></button>
<%else%>
  <button type="button" class="btn btn-info"><%= link_to 'Log in', new_session_path%></button> 
<%end%>

</div>